### ISSUE TITLE
Markbot saying rocket.svg is too large

### ISSUE THREAD

**Issue by jen-power** [jen-power/but-em-buttons#1]
@charlie-quinn

I've opened the rocket.ai file from the prod folder given to us, changed the artboard to Fit to Artwork Bounds, Exported for Screens, saved as an .svg and then dropped into Spritebot. Spritebot shows that the file is 0.993 kB but Markbot is still saying it is 2 kB. 

Not sure how else to make this file smaller and appease Markbot?

<img width="736" alt="rocket-spritebot" src="https://user-images.githubusercontent.com/43247074/66436079-390dab80-e9f4-11e9-9323-5e4542415e11.png">

**Comment by charlie-quinn** [comment]
- [ ] resize artwork in AI to be 100px in height
  - this asset is pretty small on our site, so we don't need it to be any larger than this
- [ ] smush it using `spritebot` and/or [svgomg](https://jakearchibald.github.io/svgomg/)
Markbot should be much happier 🤖🎉

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`
